PREFIX :<http://cedric.cnam.fr/isid/ontologies/OntoSemStats.owl#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX void:<http://rdfs.org/ns/void#>
# CONSTRUCT 
# {
#     _:b0 a void:Dataset ; :hasStat [
#         a :Stat ; :hasSemanticFeature :OwlFunctionalProperty ;
#         :definitionCount ?definitionsCount ; 
#         :usageCount ?triples ]
# }
SELECT ?definitionsCount ?triples ?feature
WHERE
{
    values ?feature { :OwlFunctionalProperty }
    # {
    #     SELECT (if(bound(?ds), ?ds, dbo:Person) as ?dataset)
    #     WHERE
    #     {            
    #         OPTIONAL {?ds a void:Dataset .}
    #         # BIND(IF(BOUND(?ds), ?ds, _:b0) AS ?dataset)
    #     }
    # }
    {
        SELECT (COUNT (DISTINCT ?p) as ?definitionsCount)
        WHERE 
        {
            {
                ?p a owl:FunctionalProperty .
            } 
            UNION
            {
                ?p2 a owl:FunctionalProperty .
                ?p (rdfs:subPropertyOf|owl:equivalentProperty)+ ?p2 .
            }
        }
    }
    {
        SELECT (COUNT (*) as ?triples)
        WHERE
        {
            {
                SELECT DISTINCT ?p
                WHERE 
                {
                    {
                        ?p a owl:FunctionalProperty .
                    } 
                    UNION
                    {
                        ?p2 a owl:FunctionalProperty .
                        ?p (rdfs:subPropertyOf|owl:equivalentProperty)+ ?p2 .                        
                    } 
                }
            }
            ?s ?p ?o .
        }
    }
}