PREFIX :<http://cedric.cnam.fr/isid/ontologies/OntoSemStats.owl#>
PREFIX rdfs:<http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:<http://www.w3.org/2002/07/owl#>
PREFIX void:<http://rdfs.org/ns/void#>
# CONSTRUCT 
# {
#     _:b0 a void:Dataset ; :hasStat [
#         a :Stat ; :hasSemanticFeature :OwlDifferentFrom ;
#         :definitionCount ?definitionsCount ]
# }
SELECT ?definitionsCount ?feature
WHERE
{
    values ?feature { :OwlDifferentFrom }
    {
        SELECT (COUNT (*) as ?definitionsCount)
        WHERE 
        {
            {
                ?p owl:differentFrom ?p2 .
            } 
        }
    }
}